/*
 * Los textos que el diagrama de objetos escribe por su cuenta, en los dos
 * idiomas. Por defecto, y con --enlang o --enarticlelang, sale todo en ingles;
 * con los modos --es..., en
 * castellano.
 *
 * Aca van SOLO los textos que pone la herramienta. Lo que viene de tu codigo no
 * se traduce nunca, porque no es texto sino nombres: `Persona`, `celular`,
 * `juliana`, las lineas del .wrepl al pie de la secuencia, los valores de tus
 * strings. Tampoco los mensajes de error que devuelve el interprete de Wollok,
 * que no son de esta herramienta.
 *
 * Tampoco los ids internos (`ambiente`, `paso-3`): no se ven, y son el ancla de
 * las posiciones guardadas. Traducirlos perderia lo acomodado a mano.
 */

import { isEnglish } from '../wollok-uml/objects.mjs'

const TEXTS = {
	es: {
		environment: 'Ambiente',
		objectDiagram: 'Diagrama de objetos',
		construction: 'Construcción',
		initialState: 'Estado inicial',
		generatedFrom: 'Generado por tools/wollokdd2drawio a partir de:',
		withoutRepl: '(sin .wrepl: solo los WKO del modelo)',
		doNotEdit: 'No editar a mano: volver a generarlo.',
	},
	en: {
		environment: 'Environment',
		objectDiagram: 'Object diagram',
		construction: 'Construction',
		initialState: 'Initial state',
		generatedFrom: 'Generated by tools/wollokdd2drawio from:',
		withoutRepl: "(no .wrepl: only the model's WKOs)",
		doNotEdit: 'Do not edit by hand: regenerate it instead.',
	},
}

/** @param language  uno de LANGUAGES de objects.mjs: los dos modos en ingles dan ingles */
export const textsFor = (language) => TEXTS[isEnglish(language) ? 'en' : 'es']
