/*
 * El armado comun a las dos herramientas: leer argumentos, leer fuentes,
 * construir el entorno de Wollok, cargar el sidecar y extraer el modelo UML.
 *
 * Lo unico que cambia entre wolloksd2puml y wolloksd2drawio es el `render`.
 */

import { writeFile } from 'node:fs/promises'
import { relative, sep } from 'node:path'
import { readSources } from './sources.mjs'
import { loadConfig } from './config.mjs'
import { importWollokTs } from './wollok.mjs'
import { extractModel } from './extract.mjs'
import { DEFAULT_LANGUAGE, LANGUAGE_FLAGS, messagesFor } from './i18n.mjs'

/** Lo que este modulo le dice al usuario. Mismas claves en los dos idiomas. */
const MESSAGES = {
	en: {
		derivedInterfaces: (count, names) => `${count} interface(s) inferred from the polymorphic families: ${names.join(', ')}`,
		summary: (entities, interfaces, relations) => `${entities} entities, ${interfaces} interfaces, ${relations} relationships`,
		warningsHeader: (count) => `${count} thing(s) I couldn't infer from the code:`,
		generatedBy: (toolName, names) => `Generated by tools/${toolName} from: ${names.join(', ')}`,
		doNotEdit: 'Do not edit by hand: regenerate it instead.',
		configuration: (path) => `Configuration: ${path}`,
	},
	es: {
		derivedInterfaces: (count, names) => `${count} interfaz(ces) deducida(s) de las familias polimorficas: ${names.join(', ')}`,
		summary: (entities, interfaces, relations) => `${entities} entidades, ${interfaces} interfaces, ${relations} relaciones`,
		warningsHeader: (count) => `${count} cosa(s) que no pude deducir del codigo:`,
		generatedBy: (toolName, names) => `Generado por tools/${toolName} a partir de: ${names.join(', ')}`,
		doNotEdit: 'No editar a mano: volver a generarlo.',
		configuration: (path) => `Configuracion: ${path}`,
	},
}

/** Opciones que entienden las dos herramientas. */
const COMMON_OPTIONS = {
	'-o': (o, v) => { o.output = v() },
	'--output': (o, v) => { o.output = v() },
	'-c': (o, v) => { o.config = v() },
	'--config': (o, v) => { o.config = v() },
	'-t': (o, v) => { o.title = v() },
	'--title': (o, v) => { o.title = v() },
	'--associations': (o, v) => { o.associations = v() },
	'--no-attributes': (o) => { o.showAttributes = false },
	'--no-operations': (o) => { o.showOperations = false },
	'--no-mutability': (o) => { o.showMutability = false },
	// Apaga TODA la inferencia de familias polimorficas: ni interfaces deducidas
	// ni color por familia. Es la valvula de escape por si en algun modelo la
	// heuristica agrupa cosas que no van juntas.
	'--without-inference': (o) => { o.showFamilies = false },
	// La paleta, igual que en el diagrama de objetos. Vivian solo en el CLI de
	// draw.io, y PlantUML los tomaba por nombres de archivo y se caia: el boton
	// del Estatico, que corre las dos salidas en secuencia, cortaba en la primera.
	// Si se pasan los dos, vale el ultimo.
	'--pastelcolors': (o) => { o.palette = 'pastel' },
	'--colourblind': (o) => { o.palette = 'colourblind' },
	'--include-tests': (o) => { o.includeTests = true },
	'-q': (o) => { o.quiet = true },
	'--quiet': (o) => { o.quiet = true },
	'-h': (o) => { o.help = true },
	'--help': (o) => { o.help = true },
	// El idioma de los mensajes: los mismos cinco flags del diagrama de objetos.
	// Aca no hay instancias, asi que solo cuenta el idioma. Si se pasan varios,
	// vale el ultimo.
	...Object.fromEntries(Object.entries(LANGUAGE_FLAGS).map(([flag, language]) =>
		[flag, (o) => { o.language = language }])),
}

export const parseArguments = (argv, extraOptions = {}) => {
	const handlers = { ...COMMON_OPTIONS, ...extraOptions }
	const options = {
		sources: [],
		associations: 'both',
		showAttributes: true,
		showOperations: true,
		showMutability: true,
		includeTests: false,
		quiet: false,
		language: DEFAULT_LANGUAGE,
	}
	for (let i = 0; i < argv.length; i++) {
		const handler = handlers[argv[i]]
		if (handler) handler(options, () => argv[++i])
		else options.sources.push(argv[i])
	}
	return options
}

/**
 * @param help    { en, es }: el texto de la ayuda de la herramienta en cada idioma
 * @param render  ({ model, config, options, files }) => string
 */
export const runGenerator = async ({ help, extraOptions, render }) => {
	const options = parseArguments(process.argv.slice(2), extraOptions)
	const { language } = options
	const say = messagesFor(MESSAGES, language)

	if (options.help || !options.sources.length) {
		console.log(messagesFor(help, language))
		process.exit(options.help ? 0 : 1)
	}

	const files = await readSources(options.sources, options.includeTests, { language })
	const { buildEnvironment } = await importWollokTs({ language })
	const environment = buildEnvironment(files)
	const config = await loadConfig(options)
	const model = extractModel(environment, config, { deriveInterfaces: options.showFamilies !== false, language })

	// Conviene decir cuales son las que NO escribiste vos: si te gustan, el paso
	// siguiente es declararlas con @UmlImplements y dejarlas de tu lado.
	const derived = model.interfaces.filter((entity) => entity.derived)
	if (derived.length && !options.quiet) {
		console.log(`   ${say.derivedInterfaces(derived.length, derived.map((entity) => entity.name))}`)
	}

	const output = await render({ model, config, options, files })

	if (options.output) {
		await writeFile(options.output, output, 'utf8')
		console.log(`✓ ${options.output}  (${say.summary(model.entities.length, model.interfaces.length, model.relations.length)})`)
	} else {
		process.stdout.write(output)
	}

	if (!options.quiet && model.warnings.length) {
		console.error(`\n${say.warningsHeader(model.warnings.length)}`)
		for (const warning of model.warnings) console.error(`  - ${warning}`)
	}
}

/*
 * Igual que en sources.mjs: en la cabecera van rutas relativas y con barras
 * normales, para que el archivo generado sea el mismo se lo invoque con la ruta
 * relativa (npm run uml) o con la absoluta (el boton de VSCode).
 */
const asRelativePath = (path) => relative(process.cwd(), path).split(sep).join('/')

/**
 * Las lineas de "generado por" que las dos herramientas ponen de cabecera.
 * @param language  uno de LANGUAGES: el idioma de esas lineas
 */
export const provenanceOf = (toolName, files, config, language = DEFAULT_LANGUAGE) => {
	const say = messagesFor(MESSAGES, language)
	return [
		say.generatedBy(toolName, files.map((f) => f.name)),
		say.doNotEdit,
		...(config.configFile ? [say.configuration(asRelativePath(config.configFile))] : []),
	]
}
